project:
  type: book

book:
  title: "tMANUAL"
  date: "5/31/2023"
  chapters:
    - index.qmd
    - installing.qmd
    - navigating.qmd
    - preprocessing.qmd
    - modelling.qmd
    - plotting.qmd
    - references.qmd

bibliography: bibliography.bib

format:
  # html:
  #   theme: cosmo
  pdf:
    documentclass: scrreprt



