project:
  type: website
  output-dir: "../"

website:
  title: "tMAVEN Documentation"

  page-navigation: false
  site-url: https://GonzalezBiophysicsLab.github.io/tmaven
  repo-url: https://github.com/GonzalezBiophysicsLab/tmaven
  # repo-actions: [edit, source]

  # page-footer:
  #   left: "something 2023"

  sidebar:
    title: "(t)ime series (M)odeling, (A)nalysis, and (V)isualization (EN)vironment"
    logo: images/logo.png
    pinned: true
    tools:

      - icon: journal-text
        href: https://doi.org/10.1016/j.bpj.2024.01.022
        text: "Manuscript"
      - icon: file-earmark-text
        href: https://www.biorxiv.org/content/10.1101/2023.08.15.553409v2
        text: "Preprint"
      - icon: github
        href: https://github.com/GonzalezBiophysicsLab/tmaven
        text: "Repository"
      # - icon: hexagon
      #   href: https://GonzalezBiophysicsLab.github.io/tmaven
      #   text: "tMAVEN website"
      - icon: pen
        href: https://github.com/GonzalezBiophysicsLab/tmaven/discussions
        text: "Discussions"


    style: "floating"
    search: true
    collapse-level: 1

    contents:
      - href: index.qmd
        text: Home
      - about.qmd

      - section: "Get Started"
        contents:
          - install.qmd
          - tutorial_quickstart.qmd
          - shortcuts.qmd

          
      - section: "tMANUAL"
        contents:
          - "tmanual/web_intro.qmd"
          - "tmanual/installing.qmd"
          - "tmanual/navigating.qmd"
          - "tmanual/preprocessing.qmd"
          - "tmanual/modelling.qmd"
          - "tmanual/plotting.qmd"

      - section: "Examples"
        contents:
          - "examples/example_defaultprefs.qmd"
          - "examples/example_smdload.qmd"
          - "examples/example_script1.qmd"
          - "examples/example_rastergramplot.qmd"
          - "examples/example_entropyplot.qmd"
          - "examples/example_runhhmm.qmd"

      - section: "Information"
        contents:

          - info_priors.qmd
          - info_models.qmd
          - info_pysmd.qmd
          - develop.qmd
          # - extra_hmms.qmd

# exectue:
#   freeze: true

format:
  html:
    theme: cosmo
    code-background: true
    code-copy: true
    css: styles.css
    toc: true



